name: Test Action

on:
  push:
    branches:
      - master

jobs:

  deploy-to-ghPages:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v2
      
      - name: Install dependencies
        run : npm ci
      
      - name: Build
        run: npm run build
      
      - name: Add index.html
        run:  mv index.html ./dist
      
      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ github.token }}
          BUILD_DIR: ./dist
