name: Test Action

on:
  push:
    branches:
      - master 

jobs:

  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v2
      
      - name: Print en pantalla
        run: |
          echo "Hola cucxx!"
      
      - name: Fecha
        run: date
      
      - name: Listar files 
        run: ls -l
      
      - name: Correr file
        run: npm run build
