name: Test Action

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:

  deploy-to-ghPages:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      #- uses: actions/setup-node@v2
      
      #- name: Install dependencies
      #  run : npm ci
      
      - name: Build
        run: npm run build
      
      - name: Add index.html to ./dist
        run:  mv index.html ./dist
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
