name: Paralel jobs

on:
   push:
     branches: ["master"]


jobs:
   
   #avoid_redundancy:
   #  runs-on: ubuntu-22.04
   #  steps:
   #   - uses: styfle/cancel-workflow-action@0.9.1
   #     with:
   #       access-token: ${{ github.token }}


   build: #compilamos codigo
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - name: Test node
         run : npm run star
       
       - name: Build Files
         run : npm run build
       
       - run : ls dist 
         
   
   test:
     needs: [build]
     runs-on: ubuntu-22.04
     steps:
       - name: Fake testing
         run : node ./dist/app.js  #fijarse si esta creando el archivo con un ls


   deploy:
     needs: [build,test]
     runs-on: ubuntu-22.04
     steps:
       - name: Fake deploy
         run : echo "Deployiing nasheee"