name: Paralel jobs

on:
   push:
     branches: ["lalalal"]


jobs:
   
   avoid_redundancy:
     runs-on: ubuntu-22.04
     steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access-token: ${{ github.token }}


   build: #compilamos codigo
     runs-on: ubuntu-22.04
     steps:
       
       - name: Checkout repo
         uses: actions/checkout@v2
         with:
           fetch-depth: 1
       
       - uses: actions/setup-node@v2

       #- name: Test node
       #  run : npm run star

       - name: Install dependencies
         run : npm ci
       
       - name: Build Files
         run : npm run build
       
       - name: Upload dist  
         uses: actions/upload-artifact@v2
         with:
            name: dist
            path: dist
         
   
   test:
     needs: [build]
     runs-on: ubuntu-22.04
     steps:
       
       - name: Checkout Repo
         uses: actions/checkout@v2
         with:
           fetch-depth: 1
       
       - name: Install dependencies
         run : npm ci

       - name: Download dist
         uses: actions/download-artifact@v2
         with:
            name: dist
            path: dist
       
       - name: Fake testing
         run : node ./dist/app.js  #nos deja hacerlo aunque no metamos la action de set up node
                                   #ni la de checkout
       
       - run: ls


   deploy:
     needs: [build,test]
     runs-on: ubuntu-22.04
     steps:
       
       - name: Download dist
         uses: actions/download-artifact@v2
         with:
            name: dist
            path: dist

       - name: Fake deploy
         run : echo "Deployiing nasheee"